DROP DATABASE IF EXISTS concert;
CREATE DATABASE `concert`;
USE `concert`;

CREATE TABLE users (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(50) NOT NULL,
  lastName VARCHAR(50) NOT NULL,
  login VARCHAR(50) NOT NULL,
  password VARCHAR(50) NOT NULL,
  VERSION INT NOT NULL,
  UNIQUE KEY login (login),
  PRIMARY KEY(id)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;

  CREATE TABLE sessions (
  idUser INT(11) NOT NULL AUTO_INCREMENT,
  token VARCHAR(50) NOT NULL,
  UNIQUE KEY token (token),
  FOREIGN KEY (idUser) REFERENCES users (id) ON DELETE CASCADE,
  PRIMARY KEY(idUser)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;


    CREATE TABLE composers (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;

  CREATE TABLE artists (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;

    CREATE TABLE wordAuthors (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;


  CREATE TABLE songs (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(50) NOT NULL,
  duration INT NOT NULL,
  idAuthorProposal INT(11),
  VERSION INT NOT NULL,
  KEY idAuthorProposal (idAuthorProposal),
  FOREIGN KEY (idAuthorProposal) REFERENCES users (id) ON DELETE SET NULL,
  PRIMARY KEY(id)
  ) ENGINE=INNODB DEFAULT CHARSET=utf8;

   CREATE TABLE songs_wordAuthors (
   idSong INT(11) NOT NULL,
   idWordAuthor INT(11) NOT NULL,
   FOREIGN KEY (idSong) REFERENCES songs (id) ON DELETE CASCADE,
   FOREIGN KEY (idWordAuthor) REFERENCES wordAuthors (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

 CREATE TABLE songs_artists (
   idSong INT(11) NOT NULL,
   idArtist INT(11) NOT NULL,
   FOREIGN KEY (idSong) REFERENCES songs (id) ON DELETE CASCADE,
   FOREIGN KEY (idArtist) REFERENCES artists (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

 CREATE TABLE songs_composers (
   idSong INT(11) NOT NULL,
   idComposer INT(11) NOT NULL,
   FOREIGN KEY (idSong) REFERENCES songs (id) ON DELETE CASCADE,
   FOREIGN KEY (idComposer) REFERENCES composers (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;


   CREATE TABLE comments (
   id INT(11) NOT NULL AUTO_INCREMENT,
   idSong INT(11) NOT NULL,
   text TINYTEXT NOT NULL,
   idAuthorProposal INT(11),
   FOREIGN KEY (idSong) REFERENCES songs (id) ON DELETE CASCADE,
   FOREIGN KEY (idAuthorProposal) REFERENCES users (id) ON DELETE SET NULL,
   PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

   CREATE TABLE userAgree (
   idUser INT(11) NOT NULL,
   idComment INT(11) NOT NULL,
   FOREIGN KEY (idUser) REFERENCES users (id) ON DELETE CASCADE,
   FOREIGN KEY (idComment) REFERENCES comments (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE ratings (
   id INT(11) NOT NULL AUTO_INCREMENT,
     idSong INT(11) NOT NULL,
     idUser INT(11) NOT NULL,
     rating INT NOT NULL,
     VERSION INT NOT NULL,
     FOREIGN KEY (idSong) REFERENCES songs (id) ON DELETE CASCADE,
     FOREIGN KEY (idUser) REFERENCES users (id) ON DELETE CASCADE,
     PRIMARY KEY(id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;


